version: '3.8'

services:
  fastapi:
    build: .
    restart: always
    expose:
      - "8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.fastapi.rule=Host(`localhost`)
      - traefik.http.routers.fastapi.rule=PathPrefix(`/`)
      - traefik.http.routers.fastapi.entrypoints=http
      - traefik.http.services.fastapi.loadbalancer.server.port=8000
    networks:
      - traefik-public

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"     
      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"     
      - "8080:8080"  
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
